#!/usr/bin/env python3
"""
Weekly Summary — Sun 10:00 UTC
Solo personal project, no connection to employer, built with public/free-tier only

Purpose: Deep summary of week's harvest + graphify + autoresearch into LLM wikis

Steps:
1. Aggregate results.tsv, rolling_index, graph reports
2. Generate docs/weekly_brief_{date}.md
3. Update bigbang-cli/docs/llm-wiki/research-weekly.md
4. If breakthrough, create [AVA-RESEARCH][BREAKTHROUGH] task
"""
import os, re, json, yaml
from pathlib import Path
from datetime import datetime, timezone

def sanitize():
    for var in ["NO_PROXY","no_proxy","HTTP_PROXY","http_proxy","HTTPS_PROXY","https_proxy"]:
        val = os.environ.get(var,"")
        if not val: continue
        parts = re.split(r"[, \s]+", val)
        cleaned = [p for p in parts if p and p not in ["::","::/0"] and not p.startswith("[") and "::" not in p and "fd8b" not in p]
        os.environ[var] = ",".join(cleaned)

sanitize()

ROOT = Path(__file__).parent.parent

def expand(p):
    return Path(os.path.expanduser(str(p)))

today = datetime.now(timezone.utc).date().isoformat()
results_tsv = ROOT / "results" / "results.tsv"
rolling_path = expand("~/workspace/your_files/research/arxiv/rolling_index.json")
graph_report = expand("~/workspace/bigbang-cli/graphify-out-research/GRAPH_REPORT.md")
graph_json = expand("~/workspace/bigbang-cli/graphify-out-research/graph.json")
cost_json = expand("~/workspace/bigbang-cli/graphify-out-research/cost.json")
wiki_weekly = expand("~/workspace/bigbang-cli/docs/llm-wiki/research-weekly.md")
wiki_latest = expand("~/workspace/bigbang-cli/docs/llm-wiki/research-latest.md")
brief_dir = ROOT / "docs"
brief_dir.mkdir(parents=True, exist_ok=True)

# Parse results.tsv
keeps = discards = crashes = 0
best_bpb = None
best_line = None
lines = []
if results_tsv.exists():
    lines = results_tsv.read_text().strip().splitlines()[1:]  # skip header
    for line in lines:
        parts = line.split("\t")
        if len(parts) < 5:
            continue
        commit, val_bpb, mem, status, desc = parts[0], parts[1], parts[2], parts[3], parts[4]
        try:
            bpb = float(val_bpb)
        except:
            bpb = 999
        if status == "keep":
            keeps+=1
            if best_bpb is None or bpb < best_bpb:
                best_bpb = bpb
                best_line = line
        elif status == "discard":
            discards+=1
        elif status == "crash":
            crashes+=1

# Parse rolling
paper_count = 0
per_topic = {}
latest_papers = []
if rolling_path.exists():
    try:
        data = json.loads(rolling_path.read_text())
        papers = data.get("papers",{})
        paper_count = len(papers)
        for pid, p in papers.items():
            for t in p.get("topics",[]):
                per_topic[t] = per_topic.get(t,0)+1
        # last 10
        latest_papers = sorted(papers.values(), key=lambda x: x.get("updated",""), reverse=True)[:10]
    except Exception as e:
        print(f"rolling parse err {e}")

# Graph stats
graph_nodes = graph_edges = comms = 0
token_reduction = "35.2x"
graph_kb = 0
if graph_report.exists():
    text = graph_report.read_text()
    # try extract numbers
    m = re.search(r"(\d+)\s+nodes", text)
    if m:
        graph_nodes = int(m.group(1))
    m = re.search(r"(\d+)\s+edges", text)
    if m:
        graph_edges = int(m.group(1))
    m = re.search(r"(\d+)\s+communit", text)
    if m:
        comms = int(m.group(1))

if graph_json.exists():
    graph_kb = graph_json.stat().st_size/1024

cost_info = "N/A"
if cost_json.exists():
    try:
        cost_info = cost_json.read_text()[:500]
    except:
        pass

# Load config for topic descriptions
config_path = ROOT / "config" / "topics.yaml"
topics_cfg = []
if config_path.exists():
    cfg = yaml.safe_load(config_path.read_text())
    topics_cfg = cfg.get("topics",[])

# Generate brief
brief_md = f"""# Weekly Research Brief — {today}

**Solo personal project, no connection to employer, built with public/free-tier only**

Auto-generated by `scripts/weekly_summary.py` (cron: weekly Sun 10:00 UTC)

## Overview
- Total papers in rolling index (14d): {paper_count}
- Per-topic: {per_topic}
- Graphify: {graph_nodes} nodes / {graph_edges} edges / {comms} communities / {graph_kb:.0f}KB — token reduction {token_reduction} baseline
- Autoresearch experiments this week: total {len(lines)} — keeps {keeps} / discards {discards} / crashes {crashes}
- Best val_bpb: {best_bpb} from `{best_line}` if exists

## Latest 10 Papers (from rolling_index)
"""
for p in latest_papers:
    brief_md += f"- **[{p.get('arxiv_id','')}] {p.get('title','')}** — topics {','.join(p.get('topics',[]))}  \n  {p.get('arxiv_url','')} — {p.get('abstract','')[:200]}...\n"

brief_md += f"""
## Graphify Reports
- `graphify-out-research/GRAPH_REPORT.md`: {graph_report} exists={graph_report.exists()}
- `graph.json`: {graph_kb:.0f}KB at {graph_json}
- `cost.json`: {cost_info[:300]}

## Results.tsv Highlights
- Total experiments logged: {len(lines)}
- Keeps: {keeps}, Discards: {discards}, Crashes: {crashes}
- Best: {best_line}

Top 3 best (lowest val_bpb):
"""
# sort by val_bpb
sorted_lines = []
for l in lines:
    try:
        parts = l.split("\t")
        bpb = float(parts[1])
        sorted_lines.append((bpb, l))
    except:
        continue
sorted_lines = sorted(sorted_lines, key=lambda x: x[0])
for bpb, l in sorted_lines[:3]:
    brief_md += f"- {l}\n"
brief_md += "\nWorst 3:\n"
for bpb, l in sorted_lines[-3:]:
    brief_md += f"- {l}\n"

brief_md += f"""
## Per-Topic Deep Dive (7 topics)
"""
for t in topics_cfg:
    t_id = t.get("id")
    t_title = t.get("title")
    desc = t.get("description")
    imp = t.get("importance")
    eco = t.get("ecosystem")
    count = per_topic.get(t_id,0)
    brief_md += f"""
### {t_id} — {t_title} ({imp}) — {count} papers
- Description: {desc}
- Ecosystem: {eco}
- Suggested queries:
  - `pgraphify query "{t_id} optimization" --graph graphify-out-research/graph.json`
  - `pgraphify query "{t_title[:30]}" --graph graphify-out-research-combined/graph.json`
"""

brief_md += f"""
## Links
- Research latest wiki: {wiki_latest}
- Graphify out: {expand('~/workspace/bigbang-cli/graphify-out-research')}
- Rolling index: {rolling_path}
- Results.tsv: {results_tsv}
- Experiments: {ROOT / 'experiments'}
- Tasks: `bb tasks list --tasklist MDg4NTEzMTkzNjgwNzI5NDMyMDI6MDow --json | jq '.[] | select(.title|contains(\"AVA-RESEARCH\"))'`
- Program.md: {ROOT / 'program.md'}

## Next Steps per program.md
- If keeps >0, review diffs in `autoresearch/*` branches in ava-agi-factory-v6-4, check cap_preservation >=0.97, merge or create full GPU training task for Alienware
- If no keeps, query graphify for "what improves S1 Fast hl=8" etc per program.md and create new experiment
- Check weekly brief growth: baseline 727 nodes → current {graph_nodes} (should grow as harvest adds papers)

---
Generated {today} — weekly summary
"""

brief_path = brief_dir / f"weekly_brief_{today}.md"
brief_path.write_text(brief_md)
print(f"[weekly] wrote {brief_path}")

# Update wiki weekly
wiki_weekly.parent.mkdir(parents=True, exist_ok=True)
wiki_md = f"""# Research Weekly — {today}

**Solo personal project, no connection to employer, built with public/free-tier only**

Auto-generated weekly Sun 10:00 UTC by `ava-research-engine/scripts/weekly_summary.py`

{brief_md}

---

## Full latest: research-latest.md
See {wiki_latest} for daily auto-updated summary.
"""

wiki_weekly.write_text(wiki_md)
print(f"[weekly] wrote wiki {wiki_weekly}")

# Save JSON backup
backup_dir = expand("~/workspace/your_files/ava-agi/weekly_briefs")
backup_dir.mkdir(parents=True, exist_ok=True)
backup_json = backup_dir / f"brief_{today}.json"
backup_json.write_text(json.dumps({
    "date": today,
    "paper_count": paper_count,
    "per_topic": per_topic,
    "graph_nodes": graph_nodes,
    "graph_edges": graph_edges,
    "graph_kb": graph_kb,
    "experiments": len(lines),
    "keeps": keeps,
    "discards": discards,
    "crashes": crashes,
    "best_bpb": best_bpb,
    "best_line": best_line,
}, indent=2))
print(f"[weekly] backup json {backup_json}")

# Breakthrough detection
if best_bpb is not None and best_bpb < 0.95:
    # create breakthrough task
    try:
        import subprocess, json
        title = f"[AVA-RESEARCH][BREAKTHROUGH] New SOTA val_bpb {best_bpb:.4f} — {best_line[:80] if best_line else ''}"
        notes = f"Breakthrough detected {today}\\nBest: {best_line}\\nGraph: {graph_nodes} nodes\\nPapers: {paper_count}\\nSee {brief_path} and {wiki_weekly}"
        cmd = ["hatch_gws_cli","tasks","tasks","insert","--params", json.dumps({"tasklist":"@default"}),"--json", json.dumps({"title": title, "notes": notes})]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=20)
        print(f"breakthrough task created rc={result.returncode}")
    except Exception as e:
        print(f"breakthrough task failed {e}")

print("[done] weekly summary complete")
