#!/usr/bin/env python3
"""Vendor the router's MoMA-lite heuristic into lib/moma_lite.py (build step).

Vercel deploys apps/dottie-harness-api on its own, so the function cannot
import packages/dottie-loop at runtime. Instead of a hand-maintained copy (the
old lib/production_routing.py classifier, which had drifted from the router),
this script copies the MoMA-lite section of
``packages/dottie-loop/dottie_loop/backends.py`` verbatim and stamps it with the
source's sha256. ``--check`` fails when the vendored file is not exactly what
the script would write now; tests/test_production_routing_parity.py runs it and
checks production routing against the router's goldens.

    python scripts/vendor_router.py          # write lib/moma_lite.py
    python scripts/vendor_router.py --check  # exit 1 when stale
"""

from __future__ import annotations

import hashlib
import sys
from pathlib import Path

PKG = Path(__file__).resolve().parents[1]
REPO = PKG.parents[1]
SOURCE = REPO / "packages" / "dottie-loop" / "dottie_loop" / "backends.py"
TARGET = PKG / "lib" / "moma_lite.py"
START = "#: The five MoMA-lite tiers"
END = "# --- backends ---"


def render() -> str:
    text = SOURCE.read_text(encoding="utf-8")
    i, j = text.index(START), text.index(END)
    region = text[i:j].rstrip() + "\n"
    sha = hashlib.sha256(region.encode("utf-8")).hexdigest()
    return (
        '"""GENERATED by scripts/vendor_router.py -- do not edit.\n\n'
        "The MoMA-lite heuristic, copied verbatim from the router's one implementation,\n"
        "packages/dottie-loop/dottie_loop/backends.py (section sha256 below), because\n"
        "Vercel packages this app without the monorepo. lib/production_routing.py\n"
        "wraps it with the API's fail-closed guards.\n\n"
        f"source section sha256: {sha}\n"
        '"""\n\n'
        "# ruff: noqa\n"
        "from __future__ import annotations\n\n"
        "import hashlib\n"
        "import re\n"
        "from typing import Any\n\n"
        + region
    )


def main(argv: list[str]) -> int:
    want = render()
    if "--check" in argv:
        have = TARGET.read_text(encoding="utf-8") if TARGET.is_file() else ""
        if have != want:
            print(f"{TARGET} is stale: run python {Path(__file__).relative_to(REPO)}", file=sys.stderr)
            return 1
        print(f"{TARGET.relative_to(REPO)} matches {SOURCE.relative_to(REPO)}")
        return 0
    TARGET.write_text(want, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
