"""GENERATED by scripts/vendor_router.py -- do not edit.

The MoMA-lite heuristic, copied verbatim from the router's one implementation,
packages/dottie-loop/dottie_loop/backends.py (section sha256 below), because
Vercel packages this app without the monorepo. lib/production_routing.py
wraps it with the API's fail-closed guards.

source section sha256: 5c71afa25025df7a219011245b3300328465b9c30b0a84ca271d144167303564
"""

# ruff: noqa
from __future__ import annotations

import hashlib
import re
from typing import Any

#: The five MoMA-lite tiers, cheapest first. ``dottie_loop.router.LEGACY_TIER``
#: maps each onto the spec's T0..T4.
MOMA_TIERS: dict[str, dict[str, str]] = {
    "deterministic": {"cap": "cheap", "desc": "heartbeat/monitor, pure-function, no LLM"},
    "llm": {"cap": "medium", "desc": "chat, awareness, simple decomposition"},
    "deep_research": {"cap": "heavy 9K", "desc": "5-7 sources A/B/C triangulation, contradiction matrix, freshness Aug 2026"},
    "action_operator": {"cap": "medium-verify", "desc": "gmail/calendar chain, idempotent, rollback, side_effect_class"},
    "agentic_epic": {"cap": "checkpointed 13-swarm", "desc": "opaque goals, DAG version++, bounded recovery, OODA inner"},
}
TIER_ORDER = tuple(MOMA_TIERS)

INTENT_KEYWORDS: dict[str, dict[str, Any]] = {
    "agentic_loop": {"words": ["launch", "ship", "build", "end-to-end", "loop", "factory", "close the loop"], "patterns": [r"\b12 things at once\b", r"\bopaque goal\b", r"\bkeep track\b"], "weight": 1},
    "deep_research": {"words": ["compare", "vs", "stripe", "lemon squeezy", "research", "sota", "paper", "benchmark", "triangulation", "sources"], "patterns": [r"\baug\s*2026\b", r"\b5-7 sources\b"], "weight": 1},
    "complex_action": {"words": ["gmail", "calendar", "drive", "notion", "linear", "pay", "invoice", "book", "schedule"], "patterns": [r"\btool\s*chain\b"], "weight": 1},
    "deterministic": {"words": ["heartbeat", "monitor", "cron", "tick"], "patterns": [], "weight": 1},
}

# Engineering-flavoured tokens. Must match apps/ava-factory/orchestrator_infer.py
# CODE_TERMS exactly (a frozen cross-lane featurize contract).
CODE_TERMS = frozenset({
    "code", "build", "test", "deploy", "api", "bug", "fix", "refactor",
    "cli", "pipeline", "json", "python", "script", "repo", "harness",
})
_CHAIN_RE = re.compile(r"(->|then|after|next|→)")
_TOKEN_RE = re.compile(r"[a-z0-9]+")


# --- MoMA-lite (the one implementation) ------------------------------------------


def score_intent(text: str, intent: str) -> float:
    """Keyword score of ``text`` for one intent: +1 per word, +2.5 per pattern."""
    cfg = INTENT_KEYWORDS.get(intent, {})
    t = text.lower()
    score: float = 0
    for w in cfg.get("words", []):
        if w.lower() in t:
            score += 1
    for pat in cfg.get("patterns", []):
        if re.search(pat, t, re.I):
            score += 2.5
    return score


def chain_signals(text: str) -> int:
    """Count of sequencing markers (``->``, then, after, next, →) plus a long-``and`` bonus."""
    lower = text.lower()
    words = len(text.split())
    return len(_CHAIN_RE.findall(lower)) + (1 if " and " in lower and words > 10 else 0)


def complexity(text: str) -> str:
    """simple | medium | epic, from word count and chain signals."""
    words = len(text.split())
    if words > 60 or chain_signals(text) >= 3:
        return "epic"
    if words > 18:
        return "medium"
    return "simple"


def classify_moma(text: str, intent: str, cplx: str) -> str:
    """MoMA-lite tier. First match wins, in this order."""
    t = text.lower()
    if any(k in t for k in ["heartbeat", "monitor", "tick", "cron health"]):
        return "deterministic"
    if intent == "deep_research" or any(k in t for k in ["stripe", "lemon", "triangulation", "paper", "sota", "sources"]):
        return "deep_research"
    if intent == "complex_action" or any(k in t for k in ["gmail", "calendar trick", "chain call"]):
        return "action_operator"
    if intent == "agentic_loop" or cplx == "epic":
        return "agentic_epic"
    return "llm"


def routed_agents(intent: str, cplx: str) -> list[str]:
    """Agent roster for an intent/complexity pair (unknown values take the minimal roster)."""
    if intent not in ("deep_research", "complex_action", "agentic_loop"):
        intent = "chat"
    if cplx not in ("simple", "medium", "epic"):
        cplx = "simple"
    if intent == "deep_research":
        return ["deep-researcher", "synthesist", "forensic-auditor"] if cplx != "epic" else ["deep-researcher", "synthesist", "researcher", "forensic-auditor", "critic"]
    if intent == "complex_action":
        return ["action-operator", "operator", "critic"]
    if intent == "agentic_loop":
        if cplx == "epic":
            return ["scout-prime-coordinator", "strategist", "planner", "deep-researcher", "synthesist", "builder", "operator", "action-operator", "executor", "critic", "forensic-auditor", "researcher", "communicator"]
        return ["scout-prime-coordinator", "strategist", "planner", "builder", "executor", "critic", "operator", "action-operator", "synthesist"][:5]
    if cplx == "epic":
        return ["scout-prime-coordinator", "strategist", "planner", "deep-researcher", "synthesist", "builder", "executor", "critic"]
    if cplx == "medium":
        return ["scout-prime-coordinator", "strategist", "builder"]
    return ["operator", "scout-prime-coordinator"]


def moma_route(goal: str) -> dict[str, Any]:
    """The full MoMA-lite answer for a goal.

    ``confidence`` here is the pre-existing keyword-score ratio (max score / 4,
    capped at 0.96; 0.4 when nothing matched). It is NOT a probability and the
    router never thresholds it; the key name is kept because scout, jarvisd and
    their consumers already read it.
    """
    scores = {k: score_intent(goal, k) for k in INTENT_KEYWORDS}
    best = max(scores.values())
    intent = max(scores, key=lambda k: scores[k]) if best > 0 else "llm"
    cplx = complexity(goal)
    tier = classify_moma(goal, intent, cplx)
    confidence = round(min(0.96, best / 4.0), 2) if best > 0 else 0.4
    return {
        "intent": intent,
        "intent_scores": scores,
        "complexity": cplx,
        "moma_tier": tier,
        "moma_cap": MOMA_TIERS[tier]["cap"],
        "confidence": confidence,
        "routed_agents": routed_agents(intent, cplx),
    }


def goal_features(goal: str) -> dict[str, Any]:
    """Task-relevant features of a goal, safe to log: a hash, never the text itself."""
    toks = _TOKEN_RE.findall(goal.lower())
    return {
        "goal_sha256": hashlib.sha256(goal.encode("utf-8")).hexdigest(),
        "n_words": len(goal.split()),
        "n_chars": len(goal),
        "n_chain_signals": chain_signals(goal),
        "has_code_terms": any(t in CODE_TERMS for t in toks),
        "complexity": complexity(goal),
        "intent_scores": {k: score_intent(goal, k) for k in INTENT_KEYWORDS},
        "mcp_prefix": goal.startswith("mcp:"),
    }
