"""Plugin discovery: every ``bigbang/plugins/<name>`` becomes ``scout <name>``, lazily.

scout used to import all ~70 plugin modules on every invocation (and the MCP
SDK with them) before running even ``scout route``. Now the command names and
their one-line help come from a checked-in entry table
(:mod:`bigbang.core.plugin_entries`, regenerated by
``python -m bigbang.core.plugin_loader --write-entries`` and held in sync by a
test), and a plugin module is imported only when its command is invoked (or
``scout <name> --help`` is asked for). ``scout --help`` still lists every
plugin, from the table, without importing any of them.

A plugin directory that is not in the table (a brand-new plugin) is imported
eagerly exactly as before, so nothing disappears between a new plugin and the
next table refresh.

Import failures stay silent on the command line, as they always were: a plugin
that fails to import is simply not a command. They are visible two ways:
``SCOUT_DEBUG_PLUGINS=1`` prints the traceback to stderr at the moment of
failure, and ``scout doctor`` imports every plugin and reports each failure.
"""

from __future__ import annotations

import importlib
import json
import os
import pprint
import sys
import traceback
from pathlib import Path
from typing import Any

import typer
import yaml
from typer.core import TyperGroup

PLUGINS_DIR = Path(__file__).parent.parent / "plugins"

#: plugin name -> "ExcType: message" for every plugin that failed to import in this process
LOAD_FAILURES: dict[str, str] = {}
#: name -> entry-table row for plugins registered lazily on the root app
_LAZY: dict[str, dict[str, Any]] = {}


def _load_manifest(pkg_path: Path):
    mf = pkg_path / "manifest.yaml"
    if mf.exists():
        try:
            return yaml.safe_load(mf.read_text()) or {}
        except Exception:
            return {}
    return {}


def _debug() -> bool:
    return os.environ.get("SCOUT_DEBUG_PLUGINS", "").strip().lower() in ("1", "true", "yes", "on")


def _record_failure(name: str, exc: BaseException) -> None:
    LOAD_FAILURES[name] = f"{type(exc).__name__}: {exc}"
    if _debug():
        sys.stderr.write(f"scout: plugin {name!r} failed to import\n")
        traceback.print_exception(type(exc), exc, exc.__traceback__, file=sys.stderr)


def _plugin_dirs() -> list[Path]:
    return sorted(
        p for p in PLUGINS_DIR.iterdir()
        if p.is_dir() and not p.name.startswith("__") and not p.name.startswith(".")
    )


def _import_plugin(name: str) -> Any:
    """The plugin's ``cli`` module (or its package when it has no cli.py)."""
    try:
        return importlib.import_module(f"bigbang.plugins.{name}.cli")
    except ModuleNotFoundError as exc:
        if exc.name != f"bigbang.plugins.{name}.cli":
            raise
        return importlib.import_module(f"bigbang.plugins.{name}")


def _sub_app(name: str) -> typer.Typer | None:
    """Import one plugin and return its Typer app, recording (not raising) a failure."""
    try:
        module = _import_plugin(name)
    except Exception as exc:
        _record_failure(name, exc)
        return None
    sub = getattr(module, "app", None)
    if isinstance(sub, typer.Typer):
        # store manifest on app for policy checks
        sub._bb_manifest = _load_manifest(PLUGINS_DIR / name)
        return sub
    return None


def _click_group(name: str, sub: typer.Typer) -> Any:
    """The click command ``root.add_typer(sub, name=name)`` would have produced."""
    holder = typer.Typer(rich_markup_mode="rich")
    holder.add_typer(sub, name=name)
    return typer.main.get_group(holder).commands[name]


def build_entries() -> dict[str, dict[str, Any]]:
    """Import every plugin and describe its root command (for the entry table)."""
    out: dict[str, dict[str, Any]] = {}
    for p in _plugin_dirs():
        sub = _sub_app(p.name)
        if sub is None:
            continue
        cmd = _click_group(p.name, sub)
        out[p.name] = {
            "help": cmd.help,
            "short_help": cmd.short_help,
            "hidden": bool(cmd.hidden),
            "rich_help_panel": getattr(cmd, "rich_help_panel", None),
        }
    return out


def load_entries() -> dict[str, dict[str, Any]]:
    try:
        from bigbang.core.plugin_entries import ENTRIES
    except ImportError:
        return {}
    return dict(ENTRIES)


class LazyPluginGroup(TyperGroup):
    """The root group: plugin commands resolve (import) on first use.

    While help is being rendered, a not-yet-imported plugin is shown through a
    lightweight placeholder carrying its entry-table help, so ``scout --help``
    lists everything and imports nothing.
    """

    _listing = False

    def list_commands(self, ctx: Any) -> list[str]:
        eager = super().list_commands(ctx)
        return eager + [n for n in sorted(_LAZY) if n not in self.commands]

    def get_command(self, ctx: Any, cmd_name: str) -> Any:
        cmd = self.commands.get(cmd_name)
        if cmd is not None or cmd_name not in _LAZY:
            return cmd
        entry = _LAZY[cmd_name]
        if self._listing:
            return TyperGroup(name=cmd_name, help=entry.get("help"), short_help=entry.get("short_help"),
                              hidden=bool(entry.get("hidden")), rich_help_panel=entry.get("rich_help_panel"))
        sub = _sub_app(cmd_name)
        if sub is None:
            return None  # silent, as before; SCOUT_DEBUG_PLUGINS=1 / scout doctor say why
        real = _click_group(cmd_name, sub)
        self.commands[cmd_name] = real
        return real

    def format_help(self, ctx: Any, formatter: Any) -> None:
        self._listing = True
        try:
            super().format_help(ctx, formatter)
        finally:
            self._listing = False

    def format_commands(self, ctx: Any, formatter: Any) -> None:
        self._listing = True
        try:
            super().format_commands(ctx, formatter)
        finally:
            self._listing = False


def discover_plugins(app: typer.Typer, *, lazy: bool | None = None):
    """Register every plugin on ``app``: lazily from the entry table, eagerly otherwise.

    ``lazy`` defaults to on; ``SCOUT_EAGER_PLUGINS=1`` restores the old
    import-everything behaviour (a debugging aid).
    """
    if lazy is None:
        lazy = os.environ.get("SCOUT_EAGER_PLUGINS", "").strip().lower() not in ("1", "true", "yes", "on")
    entries = load_entries() if lazy else {}
    for pkg_path in _plugin_dirs():
        name = pkg_path.name
        if name in entries:
            _LAZY[name] = entries[name]
            continue
        try:
            module = _import_plugin(name)
            sub_app = getattr(module, "app", None)
            if isinstance(sub_app, typer.Typer):
                sub_app._bb_manifest = _load_manifest(pkg_path)
                app.add_typer(sub_app, name=name)
            elif hasattr(module, "register"):
                module.register(app)
        except Exception as exc:
            # allow other plugins to load; the failure is recorded, not raised
            _record_failure(name, exc)


def check_plugins() -> dict[str, Any]:
    """Import every plugin now; ``scout doctor`` reports the result."""
    failures: dict[str, str] = {}
    names = [p.name for p in _plugin_dirs()]
    for name in names:
        try:
            _import_plugin(name)
        except Exception as exc:
            failures[name] = f"{type(exc).__name__}: {exc}"
    entries = load_entries()
    return {
        "plugins": len(names),
        "importable": len(names) - len(failures),
        "failures": failures,
        "not_in_entry_table": sorted(set(names) - set(entries)),
        "stale_entries": sorted(set(entries) - set(names)),
    }


def list_plugin_names():
    return [p.name for p in _plugin_dirs()]


def get_all_manifests():
    out = {}
    for p in _plugin_dirs():
        mf = p / "manifest.yaml"
        if mf.exists():
            try:
                out[p.name] = yaml.safe_load(mf.read_text())
            except Exception:
                out[p.name] = {}
        else:
            out[p.name] = {}
    return out


_ENTRIES_HEADER = '''"""Generated by ``python -m bigbang.core.plugin_loader --write-entries``. Do not edit.

The root help of every plugin, so ``scout --help`` lists plugins without
importing them (bigbang.core.plugin_loader). tests/test_plugin_loader.py fails
when this drifts from the plugins' real help; regenerate, do not hand-edit.
"""

ENTRIES = '''


def write_entries(path: Path | None = None) -> Path:
    target = path or Path(__file__).with_name("plugin_entries.py")
    body = pprint.pformat(build_entries(), width=100, sort_dicts=True)
    target.write_text(_ENTRIES_HEADER + body + "\n", encoding="utf-8")
    return target


if __name__ == "__main__":
    if "--write-entries" in sys.argv:
        print(write_entries())
    else:
        print(json.dumps(check_plugins(), indent=2))
