#!/usr/bin/env python3
"""Render bench/report.md from results.json + metrics.json.

Verdict-first, <=10 lines per workflow, honest gaps. Blocked workflows are
reported as BLOCKED with their reason — never as success.
"""
from __future__ import annotations

import json
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "out"


def main():
    results = {r["id"]: r for r in
               json.loads((OUT / "results.json").read_text())["results"]}
    m = json.loads((OUT / "metrics.json").read_text())
    per = m["per_workflow"]
    ts = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())

    verdict = ("PASS" if m["n_blocked"] == 0 and m["n_ok"] == m["n_workflows"]
               else "PARTIAL" if m["n_ok"] > 0 else "FAIL")
    lines = [
        f"# Dottie harness benchmark — {ts}",
        "",
        f"**Verdict: {verdict}** — {m['n_ok']}/{m['n_workflows']} workflows ok, "
        f"{m['n_blocked']} blocked, harness_score={m['harness_score']}, "
        f"tokens_est={m['total_tokens_est']} (heuristic, chars/4).",
        "",
        "Mode: dry-run / read-only. Nothing merged, deployed, posted, or written "
        "outside bench temp dirs. `blocked` is a measured result, not a skip.",
        "",
    ]
    for wid, p in per.items():
        r = results[wid]
        mark = "OK" if p["score"] == 1.0 else ("BLOCKED" if p["status"] == "blocked" else "FAIL")
        body = [
            f"## [{mark}] {p['name']}",
            f"- id `{wid}` · category {p['category']} · exit={p['exit_code']}",
            f"- latency p50={p['p50_latency_ms']}ms · tokens_est={p['tokens_est']}",
            f"- correctness: {p['correctness'][:400]}",
        ]
        # gap line: what is still unmeasured or caveated
        gap = None
        if p["status"] == "blocked":
            gap = f"GAP: {p['correctness'][:200]}"
        elif wid == "grpo_collect" and "synthetic" in p["correctness"].lower():
            gap = ("GAP: canonical run flagged synthetic=True — outputs are structurally "
                   "valid but the trace source is synthetic; not a production-data signal.")
        elif wid in ("retrieval_commit", "retrieval_task"):
            gap = ("NOTE: BM25 baseline only; numbers compare retrievers on identical "
                   "queries/judgements, not absolute retrieval quality (see script headers).")
        elif wid == "goal_intake":
            gap = "NOTE: read-only drain; posting path and corrupt-state fail-closed branch not exercised."
        elif wid == "gate_audit" and "NEW un-baselined" in p["correctness"]:
            gap = ("GAP: new fail-open candidates await human judgement against "
                   "scripts/gate_audit_baseline.json — the audit is working, the repo has drift.")
        if gap:
            body.append(f"- {gap}")
        lines.extend(body + [""])
        assert len(body) <= 10, wid

    lines += [
        "## Category rollup",
        "",
    ]
    for c, v in m["by_category"].items():
        lines.append(f"- {c}: mean_score={v['mean_score']} over {', '.join(v['workflows'])}")
    lines += [
        "",
        "_Generated by bench/report.py. Re-run: `python3 bench/runner.py && "
        "python3 bench/metrics.py && python3 bench/report.py`._",
    ]
    (HERE / "report.md").write_text("\n".join(lines))
    print(f"report: verdict={verdict} wrote {HERE / 'report.md'}")


if __name__ == "__main__":
    main()
